# Generated by Django 5.2.11 on 2026-02-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='provider_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
