# Generated by Django 5.2.11 on 2026-02-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('room_service', 'Room Service'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('encrypted_notes', models.TextField(blank=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('encrypted_notes_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
